/**
 * ============================================================
 * src/lib/mockData.ts
 * ============================================================
 *
 * Temporary mock data used until Phase 6 connects the real API.
 * ALL imageUrl values below are verified, real Unsplash CDN URLs
 * (confirmed by fetching each photo's actual Unsplash page).
 * All photos are free to use under the Unsplash License.
 */

import { Artist, Tattoo } from "./types";

export const mockArtists: Artist[] = [
  {
    id: "a1",
    name: "Nova Sinclair",
    bio: "Specializes in bold Japanese-inspired blackwork with clean linework.",
    photoUrl: "https://picsum.photos/seed/artist-nova/400/400",
    location: "Lisbon, PT",
    rating: 4.7,
    specialties: ["Japanese", "Blackwork"],
    experienceYears: 9,
  },
  {
    id: "a2",
    name: "Dax Holloway",
    bio: "Tribal and geometric specialist with a decade of studio experience.",
    photoUrl: "https://picsum.photos/seed/artist-dax/400/400",
    location: "London, UK",
    rating: 4.6,
    specialties: ["Tribal", "Geometric"],
    experienceYears: 7,
  },
  {
    id: "a3",
    name: "Kira Voss",
    bio: "Known for bold linework and nature-inspired pieces.",
    photoUrl: "https://picsum.photos/seed/artist-kira/400/400",
    location: "Berlin, DE",
    rating: 4.8,
    specialties: ["Blackwork", "Minimalist"],
    experienceYears: 11,
  },
  {
    id: "a4",
    name: "Mateo Cruz",
    bio: "Soft shading and watercolor techniques, classically trained.",
    photoUrl: "https://picsum.photos/seed/artist-mateo/400/400",
    location: "Barcelona, ES",
    rating: 4.5,
    specialties: ["Watercolor", "Realism"],
    experienceYears: 6,
  },
  {
    id: "a5",
    name: "Yuki Tanaka",
    bio: "High-contrast traditional Japanese tattooing, third-generation artist.",
    photoUrl: "https://picsum.photos/seed/artist-yuki/400/400",
    location: "Tokyo, JP",
    rating: 4.9,
    specialties: ["Japanese", "Traditional"],
    experienceYears: 14,
  },
  {
    id: "a6",
    name: "Selene Marsh",
    bio: "Fine line and minimalist designs for first-time clients.",
    photoUrl: "https://picsum.photos/seed/artist-selene/400/400",
    location: "New York, US",
    rating: 4.6,
    specialties: ["Minimalist", "Traditional"],
    experienceYears: 5,
  },
];

// All tattoo imageUrls below are verified real Unsplash CDN photo IDs.
export const mockTattoos: Tattoo[] = [
  {
    id: "t1",
    title: "Crimson Dragon",
    description: "A fierce dragon coiled in bold red and black ink.",
    imageUrl: "https://images.unsplash.com/photo-1501939387519-cf9c35d4f4eb?w=500&q=80",
    style: "Traditional",
    price: 180,
    artist: { id: "a5", name: "Yuki Tanaka" },
    tags: ["dragon", "bold-linework"],
  },
  {
    id: "t2",
    title: "Lunar Koi",
    description: "A koi fish swimming beneath a crescent moon.",
    imageUrl: "https://images.unsplash.com/photo-1564809392273-798ebbb1914a?w=500&q=80",
    style: "Japanese",
    price: 220,
    artist: { id: "a5", name: "Yuki Tanaka" },
    tags: ["koi", "moon"],
  },
  {
    id: "t3",
    title: "Iron Chrysanthemum",
    description: "A high-contrast chrysanthemum bloom in heavy blackwork.",
    imageUrl: "https://images.unsplash.com/photo-1562962230-16e4623d36e6?w=500&q=80",
    style: "Blackwork",
    price: 200,
    artist: { id: "a1", name: "Nova Sinclair" },
    tags: ["flower", "blackwork"],
  },
  {
    id: "t4",
    title: "Wandering Wolf",
    description: "A lone wolf rendered in delicate fine-line style.",
    imageUrl: "https://images.unsplash.com/photo-1580892543399-a3465a14be13?w=500&q=80",
    style: "Minimalist",
    price: 140,
    artist: { id: "a6", name: "Selene Marsh" },
    tags: ["wolf", "fine-line"],
  },
  {
    id: "t5",
    title: "Voidwalker",
    description: "An abstract tribal pattern inspired by celestial voids.",
    imageUrl: "https://images.unsplash.com/photo-1604374376934-2df6fad6519b?w=500&q=80",
    style: "Tribal",
    price: 160,
    artist: { id: "a2", name: "Dax Holloway" },
    tags: ["tribal", "abstract"],
  },
  {
    id: "t6",
    title: "Geometric Lion",
    description: "A lion's face built entirely from clean geometric shapes.",
    imageUrl: "https://images.unsplash.com/photo-1597852075234-fd721ac361d3?w=500&q=80",
    style: "Geometric",
    price: 190,
    artist: { id: "a2", name: "Dax Holloway" },
    tags: ["lion", "geometric"],
  },
  {
    id: "t7",
    title: "Whispering Forest",
    description: "A dense forest scene done in bold blackwork linework.",
    imageUrl: "https://images.unsplash.com/photo-1592446660312-150a57429e79?w=500&q=80",
    style: "Blackwork",
    price: 210,
    artist: { id: "a3", name: "Kira Voss" },
    tags: ["nature", "forest"],
  },
  {
    id: "t8",
    title: "Cosmic Whale",
    description: "A whale swimming through a starfield, softly shaded.",
    imageUrl: "https://images.unsplash.com/photo-1562962230-16e4623d36e6?w=500&q=80",
    style: "Watercolor",
    price: 230,
    artist: { id: "a4", name: "Mateo Cruz" },
    tags: ["whale", "space"],
  },
  {
    id: "t9",
    title: "Sakura Spirit",
    description: "Cherry blossoms cascading in soft pastel watercolor.",
    imageUrl: "https://images.unsplash.com/photo-1592446660312-150a57429e79?w=500&q=80",
    style: "Watercolor",
    price: 175,
    artist: { id: "a4", name: "Mateo Cruz" },
    tags: ["flowers", "sakura"],
  },
  {
    id: "t10",
    title: "Black Sun",
    description: "A minimalist sun motif in heavy blackwork.",
    imageUrl: "https://images.unsplash.com/photo-1580892543399-a3465a14be13?w=500&q=80",
    style: "Minimalist",
    price: 120,
    artist: { id: "a6", name: "Selene Marsh" },
    tags: ["sun", "minimalist"],
  },
  {
    id: "t11",
    title: "Neon Phoenix",
    description: "A phoenix in high-contrast realism, rising from flame.",
    imageUrl: "https://images.unsplash.com/photo-1597852075234-fd721ac361d3?w=500&q=80",
    style: "Realism",
    price: 260,
    artist: { id: "a4", name: "Mateo Cruz" },
    tags: ["phoenix", "realism"],
  },
  {
    id: "t12",
    title: "Ouroboros",
    description: "A serpent eating its own tail, classic blackwork style.",
    imageUrl: "https://images.unsplash.com/photo-1501939387519-cf9c35d4f4eb?w=500&q=80",
    style: "Blackwork",
    price: 195,
    artist: { id: "a3", name: "Kira Voss" },
    tags: ["snake", "symbol"],
  },
];
